# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        validate-wrappers: true
        allow-snapshot-wrappers: true

    - name: Read Properties mod info
      id: read_version
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: gradle.properties
        properties: 'version'

    - name: Get commit sha
      id: get_commit_sha
      run: |
        short_sha=$(echo ${GITHUB_SHA} | cut -c1-7)
        echo "short_sha=$short_sha" >> $GITHUB_OUTPUT

    - name: Build with Gradle
      run: gradle shadowJar

    - name: Upload assets to GitHub Action
      uses: actions/upload-artifact@v4
      with:
        name: omms-crystal-${{ steps.read_version.outputs.version }}-${{ steps.get_commit_sha.outputs.short_sha }}
        path: |
          build/libs/*.jar
